### ISSUE TITLE
Integrate in README your article "Common Patterns With Promises"

### ISSUE THREAD

**Issue by pmusolino** [khanlou/Promise#1]
First of all, thanks for this nice and lite library!

I think that if you integrate in the readme documentation the article that you wrote here http://khanlou.com/2016/08/common-patterns-with-promises/ is a plus for everyone that want to use it.

;)
- Paolo

**Comment by khanlou** [comment]
Hi Paolo,

This library isn't production ready yet. It has tests, but I haven't used it in any projects. Also, the functions from that blog post aren't included in the code yet, because they don't have tests. I will add this information to the readme.

Soroush
