### ISSUE TITLE
Incorrect example code in Readme

### ISSUE THREAD

**Issue by SintraWorks** [khanlou/Promise#16]
In the the examples under **Ensure** and **Throwing** you write: `URLSession.shared.dataTask(with: request)` , but the dataTask itself is not a promise. Did you mean to use the data task wrapping promise created under **Creating Promises**?

    promise
      .ensure({ data, httpResponse in
          return httpResponse.statusCode == 200
      })
      .then({ data, httpResponse in
          // the statusCode is valid
      })
      .catch({ error in 
          // the network request failed, or the status code was invalid
      })

**Comment by khanlou** [comment]
It isn't clear from the readme, but it's an extension I added onto `URLSession` that sends the request and returns a promise. It works almost exactly the same as the promise above it in the readme. What do you propose for fixing the lack of clarity?

**Comment by SintraWorks** [comment]
That explains it. I had a feeling you did not simply make a mistake, but I couldn't add things up... 

Anyway, for making it clear what is going on, you could mention that you're using the extension just before the first code example that uses it. (If your extension is on GitHub, maybe add a link to it.)

And while I'm at it: many thanks for your excellent blog posts!

**Comment by SintraWorks** [comment]
I made it an excercise to recreate your URLSession extension. Any comments on the result?

    extension URLSession {
        open func dataTask(with request: URLRequest) -> Promise<(Data, HTTPURLResponse)> {
            return Promise<(Data, HTTPURLResponse)>(work: { fulfill, reject in
               self.dataTask(with: request, completionHandler: { data, response, error in
                    if let error = error {
                        reject(error)
                    } else if let data = data, let response = response as? HTTPURLResponse {
                        fulfill((data, response))
                    } else {
                        fatalError("Something has gone horribly wrong.")
                    }
                }).resume()
            })
        }
    }

**Comment by khanlou** [comment]
Nailed it! The only thing I would change is returning the promise directly instead of creating an intermediate variable and returning that.

**Comment by SintraWorks** [comment]
Thanks, getting rid of the intermediate makes sense, of course.

As an update on "fixing the lack of clarity": you could show the extension in the **Creating Promises** paragraph, right where you show how to wrap URLSession. Rather than assigning the promise to a variable, show the extension code. You wouldn't even need to adjust the the paragraph text around it, since the extension code exemplifies the idea of "wrapping" an API even more clearly than the current example.

**Comment by kelan** [comment]
@SintraWorks: Minor correction in that code listing:
I think you should use `self` instead of `URLSession.shared` in this line:
```
            URLSession.shared.dataTask(with: request, completionHandler: { data, response, error in
```
so that you make a task in the session that receives the method call, instead of always in the shared session.

**Comment by SintraWorks** [comment]
@kelan: Thanks for noticing that. You are right, of course.
