### ISSUE TITLE
Minimum deployment target iOS 9.3? Why?

### ISSUE THREAD

**Issue by romanilchyshyn** [khanlou/Promise#18]
Is it necessary to use 9.3 and not 9.0?
![screen shot 2017-03-15 at 15 26 06](https://cloud.githubusercontent.com/assets/3929184/23950613/35ad53e8-0994-11e7-9fe1-0852a3f10588.png)

**Comment by khanlou** [comment]
Nope, not necessary! Feel free to open a pull request changing it.

**Comment by romanilchyshyn** [comment]
Yes, I'll do it later in the evening. But the bad thing is that tagged version 0.1 is already with 9.3 target.
Anyway I can use commit id in Carthage, so not big problem.
