### ISSUE TITLE
macOS deployment target

### ISSUE THREAD

**Issue by Soryu** [khanlou/Promise#22]
The macOS deployment target is unset and seems to default to 10.13. I’m trying to integrate the framework via Carthage and got a compile error because my app has a 10.11 deployment target. Are you aware of this issue or maybe I’m doing something wrong. What would the minimum deployment target on Mac be? I guess the minimum version Swift 3.2 runs on. I could not find any info about this.

**Comment by khanlou** [comment]
closing!
