### ISSUE TITLE
macOS target does not include source files

### ISSUE THREAD

**Issue by Soryu** [khanlou/Promise#23]
The target membership is not set on the `Promise.swift` and `Promise+Extras.swift` files. I had some issues integrating the framework via Carthage and this was one of the things I did to fix it. Makes sense to me that the files need the target membership for the mac library to work, but I might be missing something.

**Comment by khanlou** [comment]
I don't use this framework on macOS, would you consider opening PRs to fix #22 and #23?

**Comment by khanlou** [comment]
closing!
