### ISSUE TITLE
Chaining unrelated network calls...

### ISSUE THREAD

**Issue by AaronBratcher** [khanlou/Promise#27]
This is not the best place to ask the question, but the experts are here so here goes:

If I want to chain multiple network calls, how would I go about it? Each call has a different set of parameters and returns a Promise<[String:Any]>

Ideally, I would just store the results of each .then closure and simply return the next call:

      typealias GetPromise = Promise<[String:Any]>

      getDomains(baseDomain: credentials.baseDomain).then({ domains in
         self.domains = domains
         return self.getConfiguration(baseDomain: credentials.baseDomain, brandId: credentials.brandId)
      }).then({ configuration in
         self.configuration = configuration
         return self.getServerTime(baseDomain: credentials.baseDomain)
      }).then({ serverTime in
         self.serverTime = serverTime
         resultsBlock(Results.success)
      }).catch { (error) in
         resultsBlock(Results.error(error))
      }

Unfortunately that violates the non-void return value in voice function rule.

So then I tried to return the results of each call with the promise in the next as a tuple, but that caused destructuring issues:

      typealias GetPromise = Promise<[String:Any]>

      getDomains(baseDomain: credentials.baseDomain).then({ domains in
         return (domains, self.getConfiguration(baseDomain: credentials.baseDomain, brandId: credentials.brandId))
      }).then({ (domains, configuration) in
         return (domains, configuration, self.getServerTime(baseDomain: credentials.baseDomain))
      }).then({ (domains, configuration, serverTime) in
         resultsBlock(Results.succes)
      }).catch { (error) in
         resultsBlock(Results.error(error))
      }

Here are my method definitions:

	   private func getDomains(baseDomain: String) -> GetPromise {
		  return get(urlPath: discoveryPath)
	   }
   
	   private func getConfiguration(baseDomain: String, brandId: String) -> GetPromise {
		  return get(urlPath: configurationPath)
	   }
   
	   private func getServerTime(baseDomain: String) -> GetPromise {
		  return get(urlPath: serverTimePath)
	   }
   
	   private func get(urlPath: String) -> GetPromise {
		  return GetPromise(work: { fulfill, reject in
			 guard let url = URL(string: urlPath) else {
				reject(ConnectionManager.basicError)
				return
			 }
		 
			 let task = URLSession.shared.dataTask(with: url) {(data, _, error) in
				if let error = error {
				   reject(error)
				   return
				}
			
				if let data = data
				   , let jsonObject = try? JSONSerialization.jsonObject(with: data, options: [])
				   , let dictValue = jsonObject as? [String:Any] {
				   fulfill(dictValue)
				   return
				}
			
				reject(ConnectionManager.basicError)
			 }
		 
			 task.resume()
		  })
	   }

Any ideas?

**Comment by khanlou** [comment]
This is a fine place to ask the question! You have a few options:

1) Your first bit of code works, just fine, you just need to a return type to the block. For example, `configuration -> Promise<[String: Any]> in`. This is because blocks longer than one line don't have their types inferred in Swift.
2) If all the requests are completely independent, you can use `Promises.zip`.

          Promises.zip(
               getDomains(baseDomain: credentials.baseDomain),
               self.getConfiguration(baseDomain: credentials.baseDomain, brandId: credentials.brandId),
               self.getServerTime(baseDomain: credentials.baseDomain)
          ).then({ (domains, configuration, time) in
              // save all data

Hope that helps.
