### ISSUE TITLE
error: invalid target name at 'PromiseTests'; name of non-test targets cannot end in 'Tests'

### ISSUE THREAD

**Issue by isaac-weisberg** [khanlou/Promise#32]
## Expected Behavior

1. Clone khanlou/Promise
2. Build khanlou/Promise
3. Build library
4. Link library against khanlou/Promise

## Current Behavior

```
$ swift build
Updating https://github.com/khanlou/Promise.git
Cloning https://github.com/khanlou/Promise.git
Resolving https://github.com/khanlou/Promise.git at 2.0.1
error: invalid target name at 'PromiseTests'; name of non-test targets cannot end in 'Tests'
```

## Steps to Reproduce
0. mkdir new_project && cd new_project
1. swift package init --type library && swift build && swift test
2. in Package.swift add [ .package(url: "https://github.com/khanlou/Promise.git", from: "2.0.1"), ] without sq. brackets to the array of dependencies declared as " dependencies: [ ...... ] "
3. swift build

## Context (Environment)
swift-4.0.3-RELEASE-ubuntu16.10
Lubuntu 16.10 AMD64

## Detailed Description
The issue makes impossible to build with and link against this library while maintaining project using Swift Package Manager. Was not tested on macOS.

**Comment by khanlou** [comment]
Hmm, I'm not sure how best to debug this. I don't use this library with SPM. Do you have any recommendations?

**Comment by isaac-weisberg** [comment]
I am afraid, I could not possibly offer anything else other than to attempt to use it this way, but if it's out of practice, this issue is not a very big problem since not a lot of people at all use Swift on Linux.

**Comment by isaac-weisberg** [comment]
Although no one asked, I should also note that in "Steps to Reproduce" section I do add the **package dependency**, but I do not bother to add a **target dependency**, which seals module invisible, impossible to import, not found. Thus, in a case where the dependency is compile-able on Linux, the result of "Steps to Reproduce" would still not work.
