### ISSUE TITLE
Promise chaining after `catch` is lacking

### ISSUE THREAD

**Issue by isaac-weisberg** [khanlou/Promise#42]
`then` clause comes in 3 different variants
```
public func then<NewValue>(on queue: ExecutionContext = default, _ onFulfilled: @escaping (Value) throws -> Promise.Promise<NewValue>) -> Promise.Promise<NewValue>

public func then<NewValue>(on queue: ExecutionContext = default, _ onFulfilled: @escaping (Value) throws -> NewValue) -> Promise.Promise<NewValue>

public func then(on queue: ExecutionContext = default, _ onFulfilled: @escaping (Value) -> (), _ onRejected: @escaping (Error) -> () = default) -> Promise.Promise<Value>
```
This allows for promise chaining, one of the core concepts of promises, a feature of Javascript promises.

However, for some reason there is no such option for `catch` clauses and there is only one variant
```
public func `catch`(on queue: ExecutionContext = default, _ onRejected: @escaping (Error) -> ()) -> Promise.Promise<Value>
```
What is the opinion about this functionality? Seems pretty core for me, should be added at some point. @khanlou what can you say?

**Comment by khanlou** [comment]
There is a version of `catch` called `recover` which lets you take an error, check it, and return a new promise. You can also rethrow from inside it.

https://github.com/khanlou/Promise/blob/master/Promise/Promise%2BExtras.swift#L152-L162

There is a space for a "map" version that takes an error and returns a T, but i don't think this is as valuable.

**Comment by isaac-weisberg** [comment]
Actually, yes, the behavior of recover is exactly that
