### ISSUE TITLE
As of #43, the project might be incompatible with Xcode prior to 9.3 GM and Swift prior to 4.1

### ISSUE THREAD

**Issue by isaac-weisberg** [khanlou/Promise#45]
The issue is discussed in commets to #43 . I will attempt to confirm this behavior today by attempting to compile master with the older toolchain. However the issue has been observed by the original PR creator when Travis said that there is no such function as `compactMap` since it's been added in Swift 4.1's stdlib. Overall, the #43 has essentially destroyed all the backwards compatibility that there could be.

**Comment by isaac-weisberg** [comment]
Considering this breaking change in stdlib's API, my suggestion number one is to establish continuous integration running more platforms, in particular of course, latest 4.0.x and latest 4.1.x, same with Xcode, 9.2 GM and 9.3 GM

**Comment by MrNickBarker** [comment]
I have submitted #46 to fix this issue. I have tested it with Xcode 9.2 and 9.3.

Unfortunately I don't have much experience with Travis CI so adding more platforms with different swift versions would take me a while to figure out, so preferably someone more experienced can do it.

**Comment by isaac-weisberg** [comment]
@MrNickBarker appreciating your rapid response! I will add another Build Job with older Xcode and older Swift on Linux in a separate PR.
