### ISSUE TITLE
What about 2.0.2 ?

### ISSUE THREAD

**Issue by isaac-weisberg** [khanlou/Promise#50]
There haven't been a lot of implementations' changes
There hasn't been a single API change
But still, there is 30+ commits to master since Feb, so I thought maybe it would be nice to bundle all the changes, especially getting that a public beta version of Xcode 10 is already out.

**Comment by isaac-weisberg** [comment]
Yes, I understand that these barely even change anything in the actual binary.

**Comment by khanlou** [comment]
If there were no changes, why bump the version?
