### ISSUE TITLE
Static libs now support Swift - Promise should support static libs :)

### ISSUE THREAD

**Issue by isaac-weisberg** [khanlou/Promise#51]
Since static libraries are now functioning properly with Swift and it's a release feature, why wouldn't we add 
a static library target to the podspec?

**Comment by khanlou** [comment]
Because adding new targets and ways to build the library are just more ways for it to break, I typically have avoided adding new configurations unless someone needs them. I don't see any need for static libs yet.

**Comment by isaac-weisberg** [comment]
@khanlou , alright, understood
