### ISSUE TITLE
Update Podspec

### ISSUE THREAD

**Issue by pushchris** [khanlou/Promise#52]
Would it be possible to get a new release added on so that the pod repo is up to date with some of the latest changes? The current iteration shows a compiler warning in later versions of swift due to ```compactMap``` which has been fixed in the repo but not pushed out. Thanks!

**Comment by khanlou** [comment]
This is a good idea, but I'm currently traveling. I hope to get to it soon!

**Comment by pushchris** [comment]
@khanlou thank you will look forward to it!

**Comment by mjarvis** [comment]
Ping on this -- Would be nice to have a new release available rather than using `master` 😃

**Comment by khanlou** [comment]
I was working on this today but am having trouble pushing to pod trunk. It's claiming that the library won't build with the new watchOS targets added in #49. 

The failing xcworkspace is here: [CocoaPods-Lint-20190203-6305-45fbsy-Promises.zip](https://github.com/khanlou/Promise/files/2825639/CocoaPods-Lint-20190203-6305-45fbsy-Promises.zip)

It says "Failed to install the requested application: The bundle identifier of the application could not be determined."

@startupthekid Do you think you could take a look?

**Comment by khanlou** [comment]
Still working on this — having a lot of trouble publishing to pod trunk. Hoping to have something soon.

**Comment by khanlou** [comment]
Just pushed. The trick (for future versions of Soroush) is to use the bundled version of cocoapods (which is 1.2 for some reason?)
