### ISSUE TITLE
Callback threading problems

### ISSUE THREAD

**Issue by tib** [khanlou/Promise#54]
Hi,

I just discovered an issue with the callbacks. Please run my test a couple of times in order to see what's going on (sometimes it'll fail, but sometimes it won't):

```swift
func testQueues() {
    var then: DispatchTime!
    var always: DispatchTime!
    weak var expectation = self.expectation(description: "Threading is hard!")
    Promise(value: 1)
    .then(on: DispatchQueue.global(qos: .default), { value in
        return 2
    })
    .then(on: DispatchQueue.global(qos: .background)) { value -> Promise<Int> in
        return Promise<Int>(queue: .main) { s, f in
            DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(3)) {
                s(3)
            }
        }
    }
    .then(on: DispatchQueue.global(qos: .background)) { value in
        return 4
    }
    .then(on: DispatchQueue.global(qos: .utility), { value in
        then = DispatchTime.now()
    })
    .catch(on: DispatchQueue.global(qos: .default)) { err in
        // do nothing, won't fail
    }
    .then(on: DispatchQueue.global(qos: .default)) { value in
        always = DispatchTime.now()
        XCTAssert(then != nil)
        XCTAssert(always > then)
        expectation?.fulfill()
    }
    waitForExpectations(timeout: 5, handler: nil)
}
```

The source of this problem is here:

```swift
private func fireCallbacksIfCompleted() {
    lockQueue.async(execute: {
        guard !self.state.isPending else { return }
        self.callbacks.forEach { callback in
            switch self.state {
            case let .fulfilled(value):
                callback.callFulfill(value)
            case let .rejected(error):
                callback.callReject(error)
            default:
                break
            }
        }
        self.callbacks.removeAll()
    })
}
```

This method won't wait for the previous callback to finish, so if the actual execution is on multiple threads, the callback order can be messed up. It's a pretty nasty bug. 🐛🙃

I'd suggest to use a DispatchGroup so you could get notified after a callback finished it's work. Also If you have a better alternative in order to fix this, please let me know. Thanks! 👍

**Comment by khanlou** [comment]
@tib Thanks for finding this bug. Sorry you got bitten by it! I'm a bit busy this month, but do you think you could  put together a PR to fix it? It sounds like `callFulfill` and `callReject` need to have completion blocks and include a dispatch group, as you said. It would be great if they could return promises themselves, but I don't know if that kind of recursive thing will be possible

**Comment by tib** [comment]
@khanlou as I mentioned before I already have a fix by using DispatchGroups, I was just wondering if you had a better solution in your mind. Just opened a new PR containing the fix. Feel free to review! ;)

**Comment by tib** [comment]
Thanks for merging the PR! I'll close the issue. 😉
