### ISSUE TITLE
Require only App-Extension-Safe API

### ISSUE THREAD

**Issue by patka817** [khanlou/Promise#66]
Im using this framework in an app-extension and get warning that it is not safe for use in application extension. 

The fix is quite easy, changing the build setting `Require Only App-Extension-Safe API` to `Yes` solves it.

I also wonder why UIKit is imported in the umbrella-header file and not Foundation, where the `FOUNDATION_EXPORT` is declared and there seems to be no other dependency on UIKit?

**Comment by khanlou** [comment]
If you want to make a PR for this, that would work for me!

**Comment by patka817** [comment]
> If you want to make a PR for this, that would work for me!

Great, I will be doing it when I get some time over!
