### ISSUE TITLE
Chaining problem with Promise<Any>

### ISSUE THREAD

**Issue by Soryu** [khanlou/Promise#7]
This looks like a swift compiler method matching bug, but a promise holding `Any` (e.g. used for JSON parsing) will not be used with the `flatMap` but the `map` variant of the `then` method, resulting in the promise object itself being treated as the value. See this simple snippet that can be pasted into a test class:

```swift
    func promiseAny() -> Promise<Any> {
        return Promise<Any> { fulfill, _ in
            fulfill("a")
        }
    }
    
    func testMatch() {
        let exp = expectation(description: "")
        Promise<Int>(value: 1).then { _ in
            return self.promiseAny()
        }.then { value in
            XCTAssert(value == "a")
            exp.fulfill()
        }
        waitForExpectations(timeout: 1, handler: nil)
    }
```

`value == "a"` does not compile because the compiler thinks value is of type `Promise<Any>` where it should be `Any` in my opinion. Changing the `promiseAny` function to return `Promise<String>` makes it work, though.

Maybe this is a known swift issue or maybe this is how it should work and I have it backwards, but I think this could be pointed out in the README. Or maybe you even know a way to fix it :)

Otherwise thanks for this great library. I looked at some other swift promises libs today and only this one works the way I expected it to.

**Comment by khanlou** [comment]
That's quite odd. I suspect adding a type hint in the first `then` function to explicitly say you're going to return an `Any` will also fix it.

> Otherwise thanks for this great library. I looked at some other swift promises libs today and only this one works the way I expected it to.

Thanks! That's the goal ;)

**Comment by Soryu** [comment]
Nope, adding neither `-> Any` nor `-> Promise<Any>` helps and while a force cast to String makes it compile, it crashes at runtime (because of the force cast). Anyway, not such a biggie, just thought I’d let you know. This is the only thing I stumbled over while playing with the library. Feel free to close.

**Comment by khanlou** [comment]
Wow, you're right. That's super odd. Maybe worth a Swift compiler bug report? Feel free to discuss, I'm closing in the meantime.
