### ISSUE TITLE
Conflict with State enum and @State in SwiftUI

### ISSUE THREAD

**Issue by jvtoomey** [khanlou/Promise#73]
I am playing around with SwiftUI and stated getting the error

> Generic enum 'State' cannot be used as an attribute.

on the `@State` property wrapper due to an `enum` called `State` in the Promise library.
I had to distinguish the property wrapper by naming it `@SwiftUI.State` to make the error go away.

**Comment by khanlou** [comment]
Our `State` is internal, so it shouldn't be affecting your app's module. It looks like you figured it out though?

**Comment by jvtoomey** [comment]
Wow Soroush! Pretty neat to talk to you. This library is really cool. It’s nice to use Promises just like with Javascript.
Sorry to waste your time on this. I’m just doing tiny 1-person personal projects and always found Cocoapods & Carthage confusing so I always just added your code directly. Right after posting this I remembered I should use the new Swift Package Manager, which is so much easier to wrap my head around and I realize is the right way to add external libraries, rather than my hacky method.

**Comment by khanlou** [comment]
Great to hear! Yeah, I think SPM is a little easier to work with than CocoaPods or Carthage.
